### ISSUE TITLE
Deprecate const sampling in favour of probability = 0/1

### ISSUE THREAD

**Issue by gouthamve** [jaegertracing/jaeger#1027]
The current `const` sampling is redundant because probabilistic with param: `0/1` does the same.

**Comment by gouthamve** [comment]
From the gitter channel (too bad I can't link the convo :/):

Reasons for keeping `const`:
1. probabilistic sampler calls rand(), which is not needed when you do Always/Never
2. It's more explicit

My usecase was to support `const=1` via the sampler strategies, but because it's not supported, I'm settling for `probabilistic=1`.

Now, point 1 above can be mitigated by adding checks for `param == 1/0` and for point 2, if it's being kept, I think it should be supported everywhere. Supporting it only in someplaces causes confusion.

**Comment by isaachier** [comment]
I don't really believe it makes sense to add a check just in order to delete the const sampler. I like the idea of a simple sampler for testing. To quote something I heard recently "splitters can be lumped more easily than lumpers can be split." ([Wikipedia](https://en.wikipedia.org/wiki/Lumpers_and_splitters)). By lumping both strategies into the probabilistic sampler, we make it harder to split if necessary down the line. Keeping them separate always leaves this path open for exploration.
