### ISSUE TITLE
Trace Request/Response

### ISSUE THREAD

**Issue by sameer-gupta** [jaegertracing/jaeger#1169]
Need to trace the whole request and response from different microservices.

**Comment by sameer-gupta** [comment]
Is there a way to trace whole Request and response body in jeager.

**Comment by objectiser** [comment]
Jaeger, as with any OpenTracing compliant tracer, provides the means to create spans on which the application can record tags and log events. It does not dictate what information is actually recorded on the spans.

If the application/service being traced is explicitly creating its own spans, to represent the sent/received request/response, then it can store the request/response body itself.

If your service is using an OpenTracing compliant instrumentation library (such as https://github.com/opentracing-contrib/java-web-servlet-filter) to implicitly create the spans and record standard tags, then you would need to contact that relevant instrumentation library project to see whether adding the request/response body would be possible.

However, due to the amount of additional data this would create, it would need to be an optional feature disabled by default.

**Comment by objectiser** [comment]
Closing, but feel free to re-open if you have any further questions.
