### ISSUE TITLE
Span context key and baggage prefix using 'uber'

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#121]
Wondering if the span context key and baggage prefix used for propagation could be changed from using 'uber' to being 'jaeger'?

For example:
https://github.com/uber/jaeger-client-node/blob/master/src/constants.js#L74-L77
https://github.com/uber/jaeger-client-java/blob/master/jaeger-core/src/main/java/com/uber/jaeger/propagation/TextMapCodec.java#L37-L40

**Comment by yurishkuro** [comment]
That's a difficult change when there is a large production deployment like ours. Currently we have implicit interop between tracers in 4 languages when using a default tracer initialization, which would break unless the changes are done simultaneously, and would still break in production if some services initialize tracers via default method, rather than specifying the header keys.

So it's a massive change that I don't think is worth it just to change the name. I would rather tackle it when https://github.com/TraceContext/tracecontext-spec is agreed upon, and build support for dual representation.

**Comment by objectiser** [comment]
Ok no problem - thought I would check.

**Comment by pavolloffay** [comment]
I will close this in favor of https://github.com/jaegertracing/jaeger/issues/855. 

At the moment `uber` prefix can be changed when constructing the codec (at least in java client).
