### ISSUE TITLE
Crossdock gRPC issues

### ISSUE THREAD

**Issue by isaachier** [jaegertracing/jaeger#1229]
## Requirement - what kind of business use case are you trying to solve?

I would like the crossdock tests to pass.

## Problem - what in Jaeger blocks you from solving the requirement?

gRPC communication between agent and collector fails for first one or two test traces due to `TRANSIENT_FAILURE` status in connection. This causes crossdock tests to fail consistently.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

- @yurishkuro suggests maybe using TChannel in crossdock for now until we decide how to handle the `TRANSIENT_FAILURE` issue.
- Pass `grpc.FailFast(false)` to disable the failure in the RPC between the agent and collector. The connection will wait for connection to become ready. More details here: https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md.

## Any open questions to address

How do we want to use fail fast/wait for ready behavior in general?

**Comment by yurishkuro** [comment]
Unfortunately, #1230 [did not directly help the clients](https://github.com/jaegertracing/jaeger-client-python/blob/master/crossdock/rules.mk#L3) since they still pull the yml file from docker-compose dir instead of crossdock dir. I wonder if we should use a symlink from crossdock to docker-compose after the gRPC issue is fixed

**Comment by isaachier** [comment]
Maybe this will help: https://docs.docker.com/compose/extends/#multiple-compose-files.

**Comment by pavolloffay** [comment]
Do we have a to failed travis job?

**Comment by isaachier** [comment]
Hard to find them because we usually restart them. Even when crossdock does fail, at least half the time the issue is #1221.

**Comment by yurishkuro** [comment]
Pretty much all client builds (eg Python) are failing on master

**Comment by pavolloffay** [comment]
IIRC during the call somebody mentioned that the issue happens because collector's healthcheck signals ready before grpc port if open.

We could change `StartGrpcServer` to block until clients can connect or return a channel to signal that its ready state. https://github.com/jaegertracing/jaeger/blob/master/cmd/collector/app/grpcserver/grpc_server.go#L35

**Comment by yurishkuro** [comment]
How would we do that, by querying the server from the collector itself?

Fundamentally, I think we're missing some resiliency features in the agent, ie that it loses the data even for intermittent hickup in the collector connection.

**Comment by isaachier** [comment]
@pavolloffay, I agree about the blocking/channel approach. However, gRPC seems to make it hard if not impossible to implement that. The alternative could be to wait for the server to come up using some gRPC health check mechanism in the main thread/goroutine while the server comes up in another one. That is possible, but probably not necessary/recommended by gRPC. The real solution seems to be to change all RPC to block until ready or set up a retry policy, but we should allow that to be configurable so users can tune for their systems.

**Comment by pavolloffay** [comment]
yeah I wanted to query the collector. Maybe check if the connection is in ready state on the client side. Although  I am not sure if that is enough.

**Comment by pavolloffay** [comment]
done in #1384
