### ISSUE TITLE
What happens when the jaeger-agent is down on a machine?

### ISSUE THREAD

**Issue by gvkarthik93** [jaegertracing/jaeger#1255]
What would happen to the tracing data? Can we have agent running forever on the host? Would having the agent down impact the application code?

**Comment by yurishkuro** [comment]
The client lib will be sending data to udp port that nobody will be reading from. In most cases it will be noop and the span data will get lost. In some languages the sender can sometimes get an exception that will be logged if Jaeger client is configured with a logger. There should be no impact on the application since span export happens on a separate thread.

**Comment by pravarag** [comment]
If we are using a backend data store such as Cassandra, will the data be retained if we are down on the agent node or restarted happened?
