### ISSUE TITLE
Deploying Jaeger-all-in-one to Pivotal Cloudfoundry

### ISSUE THREAD

**Issue by senattcsgit** [jaegertracing/jaeger#1275]
I'm very new to Docker and Jaeger but planning to deploy Jaeger-all-in-one to Pivotal Cloudfoundry (PCF). Once I deploy the container to PCF- trying to SSH to docker container and encountered an error. Upon reading PCF docs- PCF requires:

If you want to log in to your app container using the cf ssh command, you must make a shell such as sh or bash available in the container.

The SSH server in the container looks for the following executables in absolute locations or the PATH environment variable:

/bin/bash
/usr/local/bin/bash
/bin/sh
bash
sh

Is this possible with jaeger-all-in-one image? what should I do to achieve SSH to container?
Thanks in advance.

**Comment by yurishkuro** [comment]
Jaeger Docker images are created with `scratch` base image, it has no tooling or even shell in it, so you cannot ssh to the container. You can, however, use the image in a staged build by copying the binary to a richer base image like `alpine`.

**Comment by frankdirosaiv** [comment]
Will deploying Jaeger all-in-one image on PCF work at all? It looks like the Dockerfile for the all-in-one image exposes several [ports](https://github.com/jaegertracing/jaeger/blob/master/cmd/all-in-one/Dockerfile), but with PCF you are limited to exposing a [single port](https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html#port_config). I too have been trying to come up with a strategy to put Jaeger on PCF, but I hit this roadblock with docker.

**Comment by yurishkuro** [comment]
What is PCF?

**Comment by frankdirosaiv** [comment]
Its a PaaS. Similar to Kubernetes, PCF ([Pivotal Cloud Foundry](https://docs.pivotal.io/pivotalcf/2-1/pas/intro.html)) can be used as a container orchestration tool. PCF is where I host a lot of my applications. Pushing source code to PCF is straightforward, but pushing docker images (like @senattcsgit is trying) seems to be more restricted. I'd love to be able to use Jaeger on PCF because it is a really great tool, but I haven't had much luck.

**Comment by yurishkuro** [comment]
I don't see how you can make all-in-one work with a single port. You need at least two, one to report spans from your application, another to run the query service + UI. 

It may be possible to refactor all-in-one main function so that if it's configured with the same port for different services it will reuse the same http server. This won't be a particularly trivial change.

The single port per Docker container makes little sense. Couldn't you repeat the EXPOSE directive?

**Comment by frankdirosaiv** [comment]
I agree with you that we should be able to use multiple EXPOSE directives, but right now it seems to be a limitation of PCF. 

Perhaps deploying the Jaeger images separately (collector and query service + UI) may allow for getting around this "single exposed port" limitation?

Do you think skipping the agent image entirely and calling collector directly from the client would be a suitable strategy in this case? Discussed [here](https://github.com/jaegertracing/jaeger-client-java/issues/251)

**Comment by yurishkuro** [comment]
You can skip the agent and deploy collector and query separately. You will be running with reduced functionality though, eg no sampling config updates for the clients, no health check ports.

It actually always bothered me that we use so many ports, would be interesting to solve it (udp vs tcp would still be an issue).

**Comment by jpkrohling** [comment]
> It actually always bothered me that we use so many ports, would be interesting to solve it (udp vs tcp would still be an issue).

Other than UDP vs. TCP, I think we'd still need to split a management port from a public port. For instance, the firewall rules for the healthcheck endpoint might be different than the one for the strategy configuration or from the UI.

**Comment by yurishkuro** [comment]
Closing stale issue. We have no plans to consolidate all ports into one just to support this limitation of PCF.
