### ISSUE TITLE
add protobuf model to jaeger-idl

### ISSUE THREAD

**Issue by wuyupengwoaini** [jaegertracing/jaeger#1484]
We're ready to  use jaeger-collector to put trace datas into kafka in protobuf format,and the I go to jaeger-idl repository to find protobuf definition files,but there is only thrift format files.

So could put all the protobuf model files to jaeger-idl repository so that we can use protobuf model files to generate  model files in other language(such as java,we are going to analyse the streaming tracing data using flink in java language)

**Comment by yurishkuro** [comment]
for the record, the official proto is currently in the main repo: https://github.com/jaegertracing/jaeger/blob/master/model/proto/model.proto

**Comment by wuyupengwoaini** [comment]
But this protobufe file has some gogoprotobuf extensions which confuses develpoers

**Comment by yurishkuro** [comment]
Yes, we need to find a way to remove gogo annotations via some script.

**Comment by wuyupengwoaini** [comment]
I remove gogo annotations and generate java file and use it to serialize ,but i receieve an error
`com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type`

**Comment by yurishkuro** [comment]
Another option is not to remove gogo annotations, but use a pre-defined Docker image instead of raw protoc to compile. It would be great if someone could investigate [prototool](https://github.com/uber/prototool/) for this purpose, which comes with a Docker image that already includes gogo dependencies.

**Comment by wuyupengwoaini** [comment]
Actually,I would like to analyse tracing data in my own system and now I can not parse tracing data in protobuf format.I tried to remove gogo annotations from model.proto file ,and generate java file to parse the racing data in protobuf format,but I failed.

So Is there a effective way to do this?

**Comment by yurishkuro** [comment]
I can't help with this issue because there aren't enough details about what you do to get to this error.

I used the following class to successfully parse the protobuf messages from Kafka written there by Jaeger collector: https://github.com/PacktPublishing/Mastering-Distributed-Tracing/blob/master/Chapter12/src/main/java/io/jaegertracing/api_v2/Model.java

**Comment by yurishkuro** [comment]
The class was generated from the same proto file by removing gogo annotations.

**Comment by wuyupengwoaini** [comment]
Thanks, I'll have a try with your Model.java

**Comment by wuyupengwoaini** [comment]
Thanks,it works well
