### ISSUE TITLE
[jaeger-query] Leading zeros stripped from trace IDs 

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger#1578]
## Requirement - what kind of business use case are you trying to solve?

I would like to view traces in Jaeger UI where the trace ID has leading 0s.

## Problem - what in Jaeger blocks you from solving the requirement?

When jaeger-query returns data for traces where there are leading 0s in the trace ID, the leading 0s are stripped from the trace ID, within the data. E.g. for a trace with ID `0123`, all of the spans returned refer to trace ID `123`.

For each trace returned by jaeger-query, this applies to:

* The trace ID on the root of the trace data object
* The trace ID fields in each span
* The trace ID fields in internal references 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The zeros should not be stripped.

**Comment by yurishkuro** [comment]
Can you explain why this is a problem that 0s are stripped?

**Comment by tiffon** [comment]
The trace IDs are treated as strings, not numbers.

**Comment by yurishkuro** [comment]
I am asking what user-facing problems this issue is trying to fix, not the internal implementation details.

**Comment by tiffon** [comment]
Collapsing and expanding parents.

**Comment by yurishkuro** [comment]
So currently this is by-design behavior of the TraceID type - its `ToString()` method returns the shortest possible string representing the trace ID (essentially a base-16 number).  I think we should change it because in practice only about 4 in 64 trace IDs will start with 0, so the optimization for payload size by using shorter string doesn't make sense. 

The change does break a lot of unit tests though.

**Comment by vprithvi** [comment]
I had discussed this offline with @tiffon and came up with the alternative of the UI doing a 302 redirect from any traceID with leading 0s to a canonical traceID (shortest string representation). Do you think it's a reasonable approach?

**Comment by yurishkuro** [comment]
That would be a good thing to do in any case, because even if we make a fix on the server side, people might look up trace by ID they get from the logs, which could have leading 0s stripped. I don't think it would be a good idea to reject requests on the server if `traceID != fromHexString(traceID).toString()`

**Comment by davidmichaelkarr** [comment]
I just noticed this thread, because I think I'm running into this problem in our enterprise.  Assuming this is the same problem I'm seeing, this issue is not a cosmetic issue.  It appears that we are generating logs between different services that sometimes have the leading zero, and sometimes do not.  When we searched for a particular trace-id in our Splunk instance, we found log entries associated with the "client" service, but not the "server" service. I then dug into the actual logs and did some pattern analysis, and that's when I discovered that the logs in the "server" service had the correct trace-id, but with the leading zero removed.

If it matters, we appear to be using Jaeger version 0.33.1.

**Comment by haljin** [comment]
I'm pretty sure this is also what I am seeing. I take the trace id and convert it to a hex string in my logs and then also send data to Jaeger using Thrift. I cannot match the trace ids at all. Except sometimes I can

For example:
I get `0e7b69838055876fdf8b7ee0ecfc276a` in my logs and `e7b69838055876fa074811f1303d895` in Jaeger.

if you look at the binary representation of the upper half of the id you get:
```
0000111001111011011010011000001110000000010101011000011101101111

1110011110110110100110000011100000000101010110000111011011111010
```
The lower half in turn starts inverting bits for whatever reason. This means I cannot match what my application outputs in the logs to what I see in Jaeger  - except when the most significant bit of the id is 1 and everything matches. Except it seems it has to be 1 in both the upper and the lower half of the id - I've seen trace ID where half of it matches and the other one doesn't.
