### ISSUE TITLE
v1.14 all-in-one memory leak

### ISSUE THREAD

**Issue by skwiffhub** [jaegertracing/jaeger#1796]
## Requirement - what kind of business use case are you trying to solve?

Testing using the Jaeger client and all-in-one, with the all-in-one receiving span reports from the client and also functioning as the sampling server.

## Problem - what in Jaeger blocks you from solving the requirement?

Running under Ubuntu 16.04 (`uname -a` output: `Linux myhost 4.4.0-159-generic #187-Ubuntu SMP Thu Aug 1 16:28:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`), we observe slowly increasing memory utilization of the all-in-one in `top` output. It reached 55% `%MEM` util before we killed the all-in-one container. The memory utilization increase occurred when the all-in-one was receiving approximately 10-15 span reports per second on port 6831.

All-in-one was started as follows:
```
$ docker run --rm -p 6831:6831/udp -p 6832:6832/udp -p5778:5778/tcp -p16686:16686 jaegertracing/all-in-one:1.14 --log-level=debug
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Not sure.Appears to be a garbage collection issue somewhere in the all-in-one source code relating to span report receipt.

**Comment by jpkrohling** [comment]
The getting started does include this:

> All-in-one is an executable designed for quick local testing, launches the Jaeger UI, collector, query, and agent, with an in memory storage component.

I might be too used to Jaeger, but when I think about the fact that it has in-memory storage, it's clear to me that memory will grow in the same rate as the span ingestion. We could perhaps add an explicit call out to the `--max-traces` flag in that doc, though.

I'm open to discuss your point 1 (I think others are open too), but I'm against points 2 and 3: 

2. This will affect pretty much all current users of the in-memory storage. It will become an annoyance to everyone needing an ephemeral instance of Jaeger for quick tests, which is precisely what the in-memory is good for.

3. Storing to disk, even if at some tmpfs, is counter-productive for the in-memory, as it will require far more code than what we currently have. For local storage, we recommend using `badger` as the storage, which does provide an ephemeral mode.

In time: I believe we did talk in the past about turning badger the default storage. We haven't acted on it yet as there are a couple of things to clear first in order to "battle-test" badger. It would be very helpful if you could use badger in your setup and share your feedback! To get such an instance up and running, just set the `SPAN_STORAGE_TYPE` to badger:

```console
$ docker run -e SPAN_STORAGE_TYPE=badger jaegertracing/all-in-one:1.14
```
