### ISSUE TITLE
Why my Collectors ingest rate is higher than my Agents ingest rate?

### ISSUE THREAD

**Issue by arugifa** [jaegertracing/jaeger#1888]
I recently started to monitor my Jaeger installation with Prometheus, and noticed something a bit strange: my collectors seem to ingest more spans than what my agents are effectively sending (around 20% more). To be more precise, `jaeger_collector_spans_received_total` returns a number higher than `jaeger_agent_reporter_spans_submitted_total`.

I'm not sure I am using the right metrics here, so please correct me if I am wrong, but from what I understood:

- **spans sent by clients:** `jaeger_tracer_reporter_spans_total`
- **spans received by agents:** no metric for that
- **packets received by agents:** `jaeger_agent_thrift_udp_server_packets_processed_total`
- **spans sent by agents to collectors:** `jaeger_agent_reporter_spans_submitted_total`
- **spans received by collectors:** `jaeger_collector_spans_received_total`
- **spans saved by collectors in database:** `jaeger_collector_spans_saved_by_svc_total`

I tried to look inside the documentation and source code, but couldn't find clear answers about the exact meaning of all these metrics. So here I am :) Your help would be greatly appreciated.

**Comment by jpkrohling** [comment]
It does sound strange, but I can think of a few situations where the collector would show a number higher than the agent:

1. Clients talking directly to the collector, bypassing the agent
1. Pods being restarted, causing the agent's metrics to be restarted
1. The UI also generates spans, but you probably are accounting for that already (and it shouldn't matter much if you have quite a few spans being generated by your own application)

If you can provide the steps to consistently reproduce this situation, I could look into the code and come up with either an explanation or a bug fix, but without that, it looks like there's no real problem here.
