### ISSUE TITLE
Update thrift to 0.13

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#1972]
## Requirement - what kind of business use case are you trying to solve?

Use the most recent thrift 0.13 dependency to overcome CVEs.

## Problem - what in Jaeger blocks you from solving the requirement?

uber/tchannel-go dependency is currently using thrift 0.9.3.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Either:
1) Update tchannel-go to use thrift 0.13
2) Remove the dependency on tchannel-go.

**Comment by pavolloffay** [comment]
The thrift 0.13.0 image hasn't been published yet. It depends on this PR https://github.com/ahawkins/docker-thrift/pull/22.

https://hub.docker.com/_/thrift/?tab=description

**Comment by nilebox** [comment]
@pavolloffay any status update on this issue?

Related issue in a different project: the [OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector) includes Jaeger and Prometheus receivers, so it has Go Module dependencies on both.

When I update the Prometheus dependency to the latest v2.19.0 release, it brings the [Thrift v0.13.0 dependency](https://github.com/prometheus/prometheus/blob/v2.19.0/go.sum#L90) along, which breaks the Jaeger receiver compilation and complains about `tchannel-go` method mismatch, since it's using older Thrift version as described above.

Seems like there were breaking changes in Thrift API between v0.9.3 and v0.13.0, and the only way to fix this dependency hell is to update `uber/tchannel-go` to use `apache/thrift` v0.13.0.

**Comment by pavolloffay** [comment]
I was planning to have a look at this soon. If you have free cycles you can take it. 

Some time ago I have forked the thrift image and published 0.13.0 tag https://github.com/jaegertracing/docker-thrift

**Comment by pavolloffay** [comment]
We have removed the tchannel receiver from the collector in the previous release. Maybe there is still a reference to in the tests though.

**Comment by nilebox** [comment]
> We have removed the tchannel receiver from the collector in the previous release.

Looks like this was done in `v1.18.0`, but OpenTelemetry Collector depends on `v1.17.0`: https://github.com/open-telemetry/opentelemetry-collector/blob/b28cbd9c8e2e70bf385c3e4788ada839aa457b7d/go.mod#L28

There's actually still a dependency on `tchannel-go` in https://github.com/jaegertracing/jaeger/blob/b46738c68a906f7330e5e1a5ba6937b58e52b9dc/go.mod#L75, but it may not be needed for OpenTelemetry Collector with the latest release.

Raised the issue https://github.com/open-telemetry/opentelemetry-collector/issues/1126

**Comment by nilebox** [comment]
Note that this is still blocking Prometheus updates in OpenTelemetry Collector, see comment https://github.com/open-telemetry/opentelemetry-collector/issues/1124#issuecomment-645079077

**Comment by yurishkuro** [comment]
These are minimal direct references to tchannel-go that would need to be tackled to remove the dependency completely and upgrade Thrift:

```
./cmd/collector/app/sampling/handler.go:18:	"github.com/uber/tchannel-go/thrift"
./cmd/collector/app/span_processor.go:22:	tchannel "github.com/uber/tchannel-go"
./examples/hotrod/services/driver/server.go:21:	"github.com/uber/tchannel-go"
./examples/hotrod/services/driver/client.go:23:	"github.com/uber/tchannel-go"
```

**Comment by yurishkuro** [comment]
The examples should be re-implemented using gRPC.

**Comment by pavolloffay** [comment]
I am looking into this, first I will completely remove the dependency on `tchannel-go`.  https://github.com/jaegertracing/jaeger/issues/2129
