### ISSUE TITLE
Support batch of spans in storage writer interface

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#2142]
`SpanWriter` interface at the moment accepts a single span:
https://github.com/jaegertracing/jaeger/blob/bf64373d1e690594fd8c279720faf32722cf1494/storage/spanstore/interface.go#L28

I would like to propose to change it to work on a batch of spans instead. The reason being OTEL exporter accepts a batch of spans. This change will allow us to reuse batch and retry processor from OTEL collector
https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#batch
https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#queued-retry

This ticket should resolve:
https://github.com/jaegertracing/jaeger/issues/302
maybe https://github.com/jaegertracing/jaeger/issues/1430

**Comment by pavolloffay** [comment]
cc @jaegertracing/jaeger-maintainers

**Comment by yurishkuro** [comment]
I am not opposed to batch, but we need to define the semantics and the return value.

I assume there may be benefits to some storage implementations to work on batches instead of single spans, do we have concrete examples (Cassandra won't benefit unless spans are for the same trace). If there are no real benefits, then a simpler approach is to create a batched facade used between OTel code and SpanWriter.

**Comment by apm-opentt** [comment]
>  Cassandra won't benefit unless spans are for the same trace. 

@yurishkuro Is it possible to buffer, sort the spans periodically so you can write batch of spans that belong to the same trace?  Currently the performance hit for writing one span at a time to Cassandra is quit big.

**Comment by pavolloffay** [comment]
Elasticsearch supports batching (it is called bulk https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html). We are currently using it in Jaeger. We could drop support for it in Jaeger and instead use only OTEL batch processor. Then Elasticsearch writer will just send a bulk request per received bulk. This will have to be tested to assure that these two batch implementations are interchangeable. 

The other benefit is the OTEL queued retry processor. IIRC it retries the whole batch which at least for Elasticsearch is not ideal because of only part of the bulk request can fail (eg. some spans get stored fine and some not).

**Comment by yurishkuro** [comment]
@apm-opentt it's possible, but not recommended in the current architecture, because there's no guarantee that the spans for the same trace will be sent to the same instance of the collector/ingester. We're currently implementing aggregating collectors at Uber, which we plan to open source once it's proven in prod, there the batching will be naturally available.

**Comment by pavolloffay** [comment]
Note that Jaeger already uses ES bulk API (batching). However, we do not handle retries if the bulk fails request fails. I mention in the previous comment once we support batch in the writer interface we could use OTEL retry processor, however it retries the whole bulk.

https://github.com/jaegertracing/jaeger/blob/master/pkg/es/config/config.go#L115

**Comment by yurishkuro** [comment]
Superseded by https://github.com/jaegertracing/jaeger/issues/5079
