### ISSUE TITLE
Downsampling - is this required in OTC (or JOTC)?

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#2157]
We could add a Jaeger specific processor to provide downsampling support in JOTC if not provided in the core OTC project.

Added to acceptance criteria milestone, as intention is to have JOTC as drop in replacement for JC.

**Comment by pavolloffay** [comment]
The same behavior can be achieved by OTEL probabilistic processor https://github.com/open-telemetry/opentelemetry-collector/blob/master/processor/samplingprocessor/probabilisticsamplerprocessor/README.md#probabilistic-sampling-processor.

I don't anticipate that the downsampling flags have been widely used by the community. Instead of providing these flags in Jaeger OpenTelemetry collector we can provide a migration guide pointing out people to OTEL prob. sampler.

@yurishkuro do you agree? Can we close this issue?

**Comment by yurishkuro** [comment]
Yes, it seems like the equivalent mechanism. I think it's ok to not expose as a flag.

**Comment by pavolloffay** [comment]
Thanks for the confirmation. Then I am closing this as noop :)
