### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#2222]
This is the tracking issue for version 2.0.0.

The main purpose of this release is to change the agent, collector and ingester components to be based on the OpenTelemetry Collector.

Items to be completed:
- [ ] Replace the old binaries / images with the new OpenTelemetry Collector based (images to be named the same)
- [ ] Comparative performance analysis with current components
- [ ] UI is enhanced to natively understand OTel model (i.e. things like resources, events, links)
- [ ] The story about public APIs is better solidified - although 2.0 should only be released after stable 1.x release of OpenTelemetry Collector

Nice to haves:
- [ ] Internal data model is synced with OTel (i.e. storage APIs) - for improved performance, but as internal could be post 2.0
- [ ] Kafka messages using OTel model - possibly need to support both protocols for a while, to help with transition.

@jaegertracing/jaeger-maintainers Feel free to add further items to the list.

**Comment by objectiser** [comment]
@yurishkuro Let me know if I have misinterpreted anything.

Regarding the UI - would the model change be backward compatible or change to OTel model?

Will we be retaining the current query gRPC/protobuf endpoint be retained?

**Comment by yurishkuro** [comment]
> Regarding the UI - would the model change be backward compatible or change to OTel model?

I was referring to changing it. UI should only understand a single model, as it is too much work to keep it flexible in that respect, and the adaptation of the model can always be done in the backend. But considering that OTel data model is slightly richer than Jaeger's, it will be difficult to translate from OTel to Jaeger v1 and still maintain the same level of detail. It doesn't mean this needs to be a blocker for 2.0, but should be on the roadmap.

> Will we be retaining the current query gRPC/protobuf endpoint?

I think we want to declare a certain backwards compatibility period, say 1yr, for all earlier APIs. Even 1yr may not be enough since some organizations are not going to upgrade clients / instrumentation.

**Comment by yurishkuro** [comment]
Superseded by https://github.com/jaegertracing/jaeger/issues/4843
