### ISSUE TITLE
Can we remove specific Span from jaeger-cpp?

### ISSUE THREAD

**Issue by suab321321** [jaegertracing/jaeger#2232]

**Comment by yurishkuro** [comment]
I won'd know what this means, please explain.

**Comment by suab321321** [comment]
Hello @yurishkuro I want to know if I can remove a particular span from the tracer
`span=tracer.new_span('name')` in this way I am making a new span..but after condition check it I decide to remove this span so that it dont create extra noise in jaeger UI Is it possible?, or is there any other way to do this?

**Comment by yurishkuro** [comment]
If you never call span.finish(), then it won't be sent to the backend. But if it has other children span, then your trace will be broken, with orphan branches. You can also check your condition _before_ starting the span.

**Comment by suab321321** [comment]
@yurishkuro I m trying to achieve this using SetTag for now this will work, but here its a issue that if set a tag with same key it does not override the previous tag value. I checked there is no function to check for pre-existing tag, a function exist which only returns `vector<Tag>`
Shouldnt there should be a function to check for existing tag?

**Comment by yurishkuro** [comment]
Spans are not meant to be readable, you're already taking dependency on internal details, your code is not supposed to operate on anything but the OpenTracing API objects. Since C++ does not have a standard Context object, I assume you're propagating the context manually in a custom structure, which means you might as well store the extra details in that structure, not just the span.

**Comment by suab321321** [comment]
@yurishkuro thanks for the answers.I m closing this.
