### ISSUE TITLE
Implementing Kafka to send spans from Jaeger and then to ES without Ingester

### ISSUE THREAD

**Issue by madeinindiadot** [jaegertracing/jaeger#2271]
## Requirement - what kind of business use case are you trying to solve?
Currently I am using storage as kafka with ingester.
I am trying to setup a logstash in between kafka and ES. so that I can extract span from topic using logstash and store it in ES

## Problem - what in Jaeger blocks you from solving the requirement?

The problem is with ingester the data seems to be available in ES as-is. But with logstash I had to create a schema, filter etc to read the span data from kafka topic.
So I want to know if its possible to do handle this scenario without ingester or is it mandatory to use ingester to get the exact span data. 

## Any open questions to address

Let me know how I can implement without ingester 
If i need to use logstash is there support for Jaeger span on logstash
provide a possible or feasible solution for this appraoch

Currently I am using producer consumer encoding as protobuf

**Comment by pavolloffay** [comment]
hi @madeinindiadot. 

I am not familiar with Logstash, so I need to ask you a couple of questions. Could you please also describe why would you like to use logstash instead of Jaeger ingester? 

> So I want to know if its possible to do handle this scenario without ingester or is it mandatory to use ingester to get the exact span data.

What do you mean by _exact span data_?

The data format of spans stored in Elasticsearch is different than the format used in Kafka. Also Jaeger ES implementation used in injester/collector does more than converting the span to ES format. It also creates service indices and service data - that is needed for query service.

**Comment by madeinindiadot** [comment]
Thanks for getting back. I am using logstash already for another application which reads kafka topics and stores in ES. so planned to use the same for Jaeger span data so that it can read span data from kafka and store in ES as backend storage

**Comment by madeinindiadot** [comment]
I will still have jaeger-agent, jaeger-collector(kafka storage) and jaeger-query(ES storage) 
I planned to use logstash instead of ingester to store data in ES from Kafka.

**Comment by pavolloffay** [comment]
I am closing this as this is not feasible. The span data cannot be directly written from Kafka to ES there has the be a component that transforms data stored in Kafka to a model used in elasticsearch, in addition to that the component creates service names in the service index.
