### ISSUE TITLE
Search traces with non-string tags

### ISSUE THREAD

**Issue by idohalevi** [jaegertracing/jaeger#2540]
**Describe the bug**
When I search for traces with a tag that its value is not a string I get a 500 error. I found that the ES query contains a [regex](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html) format query. It seems like this type of query can search for string values only and when I try to search for tags that have other values I get an error.
Maybe it's related to #2364 ?

**To Reproduce**
1. Run Jaeger with ES 
2. Search for traces with tag error=true or http.status_code=200

**Expected behavior**
The expected behavior is to get all the traces with the requested tags

**Screenshots**
![image](https://user-images.githubusercontent.com/32218210/95430368-5d2c0180-0954-11eb-8c50-28d78df21cd9.png)

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.20
 - Deployment: Kubernetes

**What troubleshooting steps did you try?**
When I change the field mapping from boolean to string the search works as expected

**Comment by albertteoh** [comment]
I can look into this if there are no takers.

**Comment by objectiser** [comment]
@albertteoh All yours.

**Comment by idohalevi** [comment]
Adding some more info. Looks like there was a PR for adding regex tag search for es and I believe that since then we use regex query for every tag we have. 

This is the PR: https://github.com/jaegertracing/jaeger/pull/2049

The change from match to regex:
![image](https://user-images.githubusercontent.com/32218210/95567364-810e4680-0a2b-11eb-9208-ef138df19016.png)

**Comment by albertteoh** [comment]
As discussed with @idohalevi offline, it looks like this is not a bug with Jaeger, but the root cause was because the "vanilla" [jaeger-span index definition](https://github.com/jaegertracing/jaeger/blob/600d023800b3be0d4ec03eaabe6c4a8764a03784/plugin/storage/es/mappings/jaeger-span.json#L19) wasn't used and instead, a custom index mapping is used. 

This resulted in leaving ES to guess the best data types (dynamic mapping) for the incoming span tags which, in this case was `bool` for `error` and `long` for `http.status_code`, when they should be a `keyword`. This resulted in ES returning errors whenever we attempt to filter on `error` or `http.status_code` tags which resemble:

```
"Can only use regexp queries on keyword and text fields - not on [JaegerTag.error] which is of type [boolean]"
```

It also looks quite likely that #2049 was the cause of the issue we're seeing, as the last time tag searches on `error` was around the time of that PR.

The tradeoff for #2049, IIUC, is that we can't leverage Kibana for visualisations (e.g. line charts) of span data based on aggregations of numeric field types as Kibana will simply not show that field as an option to aggregate on if it's not numeric. 

@annanay25 is trade-off something you and the community were aware of when creating that PR?

**Comment by albertteoh** [comment]
Ah please ignore, the [jaeger-span index definition](https://github.com/jaegertracing/jaeger/blob/600d023800b3be0d4ec03eaabe6c4a8764a03784/plugin/storage/es/mappings/jaeger-span.json#L19) already defined tags as `keyword` types, well before #2049; and I can see the benefits of regex searches are more useful than numeric aggregations.

**Comment by idohalevi** [comment]
@albertteoh thanks, I'll close the issue
