### ISSUE TITLE
How to watch jaeger-agent disconnection

### ISSUE THREAD

**Issue by Asisranjan** [jaegertracing/jaeger#2619]
I am using jaeger-all-in-one docker image
When trace registered first time, everything works.
if pod/container restarts the application which generates trace is not saved and shown in Jaeger UI.

Suspecting - when pod/container restart, agent connection lost. (Please help me to correct my understanding if I am wrong)

**Comment by yurishkuro** [comment]
Which transport are you using to report spans? The default UDP does not keep connection, and expects the agent to run on the local host. However, if you run the agent under a DNS name (even if it's on the same host), then some Jaeger clients resolve DNS name to IP on start-up, so if that IP changes because of agent restart then the clients may "lose the connection". This would need to be addressed in specific clients (there were fixes in some languages, I don't recall which).

**Comment by Asisranjan** [comment]
> Which transport are you using to report spans? The default UDP does not keep connection, and expects the agent to run on the local host. 
**UDP transport**
However, if you run the agent under a DNS name (even if it's on the same host), then some Jaeger clients resolve DNS name to IP on start-up, so if that IP changes because of agent restart then the clients may "lose the connection". This would need to be addressed in specific clients (there were fixes in some languages, I don't recall which).
**Using kubernetes service name as Jaeger agent host**
**Using Jaeger Java client to report span. Is the point i mentioned a real issue? Do you have any open item to address this in java client ?**

**Comment by yurishkuro** [comment]
There were some fixes in Java and Go clients for this:
  * https://github.com/jaegertracing/jaeger-client-java/pull/726
  * https://github.com/jaegertracing/jaeger-client-go/pull/520
