### ISSUE TITLE
Amazon S3 as a storage backend

### ISSUE THREAD

**Issue by CSP197** [jaegertracing/jaeger#2633]
Update 2021-04-20: there is a plugin https://github.com/muhammadn/jaeger-s3/

Is it feasible to add Amazon S3 as a storage backend for Jaeger?

Related to #638

**Comment by yurishkuro** [comment]
Currently what Jaeger defines as "storage backend" must support (a) trace lookup by ID, and (b) indexing & searching. The former is relatively easy to do with S3 (you may even be able to use Grafana Tempo directly for that), but indexing/searching is not.

**Comment by CSP197** [comment]
Yeah, I was also looking at Grafana Labs' Tempo storage option for S3, which is why I wanted to ask if such an equivalent existed for Jaeger. 
It looks like Tempo has decoupled the trace lookup by ID function into its [Compactor](https://grafana.com/docs/tempo/latest/configuration/#compactorhttpsgithubcomgrafanatempoblobmastermodulescompactorconfiggo)

**Comment by joe-elliott** [comment]
In Tempo the querier is responsible for inspecting the backend to find the trace, but if you have questions about it it would make more sense to discuss in that repo.

**Comment by yurishkuro** [comment]
Reopening this to link to @muhammadn 's work mentioned in https://github.com/jaegertracing/jaeger/issues/638#issuecomment-820213986

**Comment by muhammadn** [comment]
@jkowall So far for testing on my local machine on a 100Mbit connection to S3 for Jaeger UI is slow but bearable since we don't look into the trace data frequently. 

We also had implemented Thanos on our infrastructure which we used to ingest the telemetric data and store on S3 and read again from S3 to Grafana so we had expected this on Jaeger-S3 plugin to Jaeger-UI.

We can live with it since there are a lot of cost savings to this. I have already added tag searches on Jaeger-S3 just a few minutes ago so that's done.

Another thing i have to fix is the time is somehow skewed and will be fixing this in a couple of days and this is the only one pending work before we run into production.

Jaeger-S3 should also be able to support storing the trace data in GCS (Google Cloud Storage) and Azure Storage Blobs and theoretically support anything that Cortex supports including Cassandra (Jaeger already has this built in but we use Cortex and Cortex supports Cassandra) Amazon DynamoDB and Google BigTable.

**Comment by joe-elliott** [comment]
Very cool! If you are looking for a trace id do you pull each db independently and search them?  Are you coordinating parallelism somehow or do you do it one at a time?

**Comment by muhammadn** [comment]
Hey @joe-elliott! Thanks! Watched your Tempo video on Youtube FOSDEM and great that you're making progress!

I have not gone through the internals of cortex on how it manages the data on object storage but from what i understand is that the indexes are stored locally and the data (in chunks) is stored in the object storage. 

Despite that i am seeing indexes being stored on s3 as well but the boltdb-shipper documentation says indexes local and data on the object storage.

The data is usually pulled when i try to find it but i realised finding by trace id is pretty snappy as data is already fetched earlier. As for the current work state, i had set the data to be fetched to be 24 hours old but i can reduce it (in `FindTraces` method) to make it fetch a lot faster.

**Comment by muhammadn** [comment]
@CSP197 @joe-elliott v1.0.0 of jaeger-s3 is released!

https://github.com/muhammadn/jaeger-s3/releases/tag/v1.0.0

**Comment by sherifkayad** [comment]
Are there any updates to this issue? .. Is it somehow planned that Jaeger would support S3 / Object storage natively?

**Comment by muhammadn** [comment]
@sherifkayad I've released version 2. This is a breaking change from version 1 where the data is not backwards compatible.

A lot of rewrite and thoughts on re-architecting jaeger-s3. Also renamed it to jaeger-objectstorage as we now support not just s3 but also AzureBlob and Google GCS. storing indexes using DynamoDB is also support now.

https://github.com/flitnetics/jaeger-objectstorage
