### ISSUE TITLE
Docker images tags, latest

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#283]
We should clarify what tags we push and also what is the latest is. 

## What can be done with `latest`?
1. point to the highest released tag. Example https://hub.docker.com/r/library/cassandra/tags/. It seems that this is usually used.
2.  push per commit in master. Example https://hub.docker.com/r/openshift/origin/tags/ It's nice for continuous delivery.

## How to handle other tags?
Currently, we push `X`, `X.Y` and `X.Y.Z`.  If there is `X.Y.Z2` then `X.Y` points to that and so on.
The latest tag should point the highest number. I think this is good and we should continue in this direction.

## What should be fixed?
1. decide on latest tag strategy.
2. use release tags for all-in-one. We could do it for all images including `test_driver`, `xdock`.
3. do not push sha and travis tags.  It seems that it is not recommended to push a lot of tags (>~100) https://forums.docker.com/t/is-there-a-max-number-of-tags-that-i-can-push-to-docker-hub-registry/1760/2. 
4. be able to get commit sha from Jaeger at runtime

**Comment by black-adder** [comment]
"latest" should point to the highest released tag but I'd also like to see a "master" (tag name up for debate) for CI (xdock tests). ie the only tags we should see for all docker containers should be "latest", "master", and "X.Y.Z"

**Comment by jpkrohling** [comment]
It's common practice in Docker to publish tags like `X`, `X.Y` and `X.Y.Z`, so that people can auto-update to the latest on that stream. Note that such tags aren't like git tags, in the sense that they aren't fixed to a specific binary: Docker images might be updated, even though the code they refer to is the same (like, when there's a security update to an underlying image).

I personally prefer `latest` to be `master`, like it's done on OpenShift. It's really helpful for daily development/demo purposes. I don't think anyone would ever consider deploying `latest` to production, no matter the approach we decide here. Doing so would imply that people are OK with automatically jumping from `0.5.0` to `2.0.0`, in the case where an initial deployment was on `0.5.0`, the pod crashed, and `2.0.0` was found as the latest when spinning a replacement pod.

**Comment by yurishkuro** [comment]
xdock images are separate anyway, and won't have x.y.z tags, so `latest` works the same for them. We need to purge those images periodically as they are created on every commit to master, and we only use latest

releasing all-in-one as numbered tag also makes sense

I don't have a strong opinion on `latest` for jaeger-xxx binaries, but have a slight preference towards only doing it for tagged commits, because doing it for every commit again creates lots of images in the Hub

**Comment by pavolloffay** [comment]
> I don't have a strong opinion on latest for jaeger-xxx binaries, but have a slight preference towards only doing it for tagged commits, because doing it for every commit again creates lots of images in the Hub

The number of images does not matter if we just update `latest`. What can be problematic is to create more than 100 tags (what we currently do).

I had also other proposal - push latest per commit for all-in-one+(xdock, test_driver). This can however create some confusion, but it's nice to have the latest features at least somewhere.

**Comment by jpkrohling** [comment]
> creates lots of images in the Hub

For our own sake's or because there is a limitation on Docker Hub? 

> What can be problematic is to create more than 100 tags (what we currently do).

Same question as above.

**Comment by pavolloffay** [comment]
@jpkrohling or @yurishkuro I don't think there is any limitation on number of pushed images. However there might be for number of tags  ( @jpkrohling see the link in my first comment, you can also find different discussions)

**Comment by objectiser** [comment]
> but it's nice to have the latest features at least somewhere.

I quite like the idea of "latest" being equivalent to "master" for both all-in-one and production images. It is good to have per commit for all-in-one for testing and demo of latest features, however the debate has been whether this is beneficial for the production images.

I think the point is that, being production images, they will only be used in a production context with a tag - and therefore for those situations having every commit pushed has no effect. But we may find situations that the feature we want to demo is based on the dependency data, or post processing pipeline, which will only be available with these production images.

So I think we should just push an image on every commit for all images.

**Comment by yurishkuro** [comment]
so:
* [ ] re-enable publishing `latest` on all commits to master -- add back `"$BRANCH" == "master" ||` to `travis/build-docker-images.sh`
* [ ] ensure that tagged versions still update `latest` -- probably will happen automatically above since we commit first and tag/release later
* [ ] remove other tags like travis build number and commit hash -- we might still want those for crossdock images

**Comment by pavolloffay** [comment]
> ensure that tagged versions still update latest -- probably will happen automatically above since we commit first and tag/release later

Just a minor comment `latest` should not updated for security/bug fixes in older releases.

**Comment by pavolloffay** [comment]
done, closing.
