### ISSUE TITLE
Flaky test TestServerGracefulExit

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#3025]
```
=== RUN   TestServerGracefulExit
    server_test.go:677: 
        	Error Trace:	server_test.go:677
        	Error:      	Should be true
        	Test:       	TestServerGracefulExit
        	Messages:   	Error log found on server exit: {{error 2021-05-21 19:22:10.814114204 +0000 UTC m=+2.124395084  Could not start HTTP server undefined } [{error 26 0  mux: server closed}]}
--- FAIL: TestServerGracefulExit (1.00s)
```
Source: `./cmd/query/app/server_test.go:651:func TestServerGracefulExit(t *testing.T)`

**Comment by albertteoh** [comment]
Why is this flaky error showing up now?
- The `mux: server closed` error was introduced in [cmux PR #69](https://github.com/soheilhy/cmux/pull/69/files#diff-b8b3fe2fb543e7b864be8c2a3b8a0637ba54362c7b3c7d98a2a4f76cc3babba3R66)
-  [cmux PR #69](https://github.com/soheilhy/cmux/pull/69/files#diff-b8b3fe2fb543e7b864be8c2a3b8a0637ba54362c7b3c7d98a2a4f76cc3babba3R66) was brought into our repo from [the cmux version bump from 0.1.4 -> 0.1.5 by dependabot](https://github.com/jaegertracing/jaeger/pull/3013) 4 days ago, hence why this flaky test has only manifested itself starting from the last few days.
- After [cmux PR #69](https://github.com/soheilhy/cmux/pull/69), [the `Accept` call returns `mux: server closed`](https://github.com/soheilhy/cmux/blob/master/cmux.go#L269) in our `TestServerGracefulExit` test because the server doesn't establish a client connection before [`server.Close()` is called in the test](https://github.com/jaegertracing/jaeger/blob/master/cmd/query/app/server_test.go#L674).

Why is it flaky?
- I think the flakiness comes down to two causes:
  - The call to `Close` will randomly [select either `case`](https://github.com/soheilhy/cmux/blob/master/cmux.go#L262). The first case returning `ErrListenerClosed` is considered normal behaviour and won't fail the test. The second case returning `ErrServerClosed` is not recognized as normal behaviour and so propagates the error, failing the test.
  - The other reason for flakiness is a race condition between when the error is logged and when it is "observed" in the test.

Why does this only relate to the HTTP server?
- The grpcServer [maintains a "connection closed" state](https://github.com/grpc/grpc-go/blob/v1.29.1/internal/grpcsync/event.go#L41), preventing it from propagating the error.
- cmux server will return `"use of closed network connection"` when the connection is closed, which is considered normal behaviour.
