### ISSUE TITLE
Report a coding bug about unused result

### ISSUE THREAD

**Issue by guodongli-google** [jaegertracing/jaeger#3361]
**Describe the bug**
At https://github.com/jaegertracing/jaeger/blob/514e72bae2abfaa1d96f26abfdc4d1bb22b8c13f/plugin/storage/cassandra/spanstore/writer.go#L242
the result of function `s.logError` is not used while while function [`logError`](https://github.com/jaegertracing/jaeger/blob/514e72bae2abfaa1d96f26abfdc4d1bb22b8c13f/plugin/storage/cassandra/spanstore/writer.go#L279-L285) returns a formatted error:
```
func (s *SpanWriter) logError(span *dbmodel.Span, err error, msg string, logger *zap.Logger) error {
	...
	return fmt.Errorf("%s: %w", msg, err)
}
```
As a consequence, the formatted result is lost.

**Expected behavior**
The result of function `s.logError` may be returned as in other places such as
https://github.com/jaegertracing/jaeger/blob/514e72bae2abfaa1d96f26abfdc4d1bb22b8c13f/plugin/storage/cassandra/spanstore/writer.go#L171

or stored into `err`:
```
		if err2 := s.writerMetrics.durationIndex.Exec(q1, s.logger); err2 != nil {
			err = s.logError(span, err2, "Cannot index duration", s.logger)
		}
```

**Additional context**
Found by static analyzer #deepgo

**Comment by zamariola** [comment]
I think I got the idea. Working on it.

**Comment by zamariola** [comment]
After the fix the concatenated error message changed 
**from**: "Failed to index duration: failed to Exec query 'select from duration_index': durationNoOperationError"
**actual**  : "Failed to index duration: Cannot index duration: failed to Exec query 'select from duration_index': durationNoOperationError"

To be honest, I prefer the older version, it's concise and non-repetitive, and the new error doesn't add any new piece of info. I'd close this issue instead of changing the return value.
