### ISSUE TITLE
Multiple systems on the same Jaeger interface

### ISSUE THREAD

**Issue by OliverJoyL** [jaegertracing/jaeger#3603]
Is it possible to use the same Jaeger to trace number of different systems and separate them by system name?

**Comment by frzifus** [comment]
What do you mean by "separate by system"?
If system means service, yes you can select different services on the start page.
![grafik](https://user-images.githubusercontent.com/10403402/160568573-2203ca25-8814-404c-8034-9e6aaa3345be.png)

**Comment by jkowall** [comment]
This is not something in the open source due to the way Jaeger handles the backend. At Logz.io we implemented multitenancy inside our multitenancy which allows for this on our service. We however do not let Jaeger manage the OpenSearch indicies since we handle that and it facilities this feature. We also have a picker that allows you to move between these subaccounts (can be used for applications or envionments).

**Comment by yurishkuro** [comment]
Sounds like a question about multi-tenancy, which is covered in #3427
