### ISSUE TITLE
go mod vendor fails when module depends on jaeger

### ISSUE THREAD

**Issue by wpcarro** [jaegertracing/jaeger#3697]
I originally reported this issue here: https://github.com/timescale/promscale/issues/1374

```
$ go mod vendor -v # from promscale repo at 0.11.0
# github.com/jaegertracing/jaeger v1.33.0
## explicit
github.com/jaegertracing/jaeger/cmd/collector/app/sampling/model
github.com/jaegertracing/jaeger/cmd/query/app
github.com/jaegertracing/jaeger/cmd/query/app/apiv3
github.com/jaegertracing/jaeger/cmd/query/app/querysvc
github.com/jaegertracing/jaeger/cmd/query/app/ui
go mod vendor: pattern actual/*: no matching files found
```

I'm posting here in case this is a bug with jaeger. As I said in the other issue, I'm a golang n00b, so I'm not sure who's (if anyone) is at fault. I'm not even sure if my expectations are correct. I just expected to be able to call `go mod vendor` on the promscale repo and have that command succeed.

Any ideas?

**Comment by yurishkuro** [comment]
it's probably because of this: https://github.com/jaegertracing/jaeger/blob/f9992f7e49532ceec92804d4cf66293b9089e1db/cmd/query/app/ui/actual.go#L28

There is no actual/ directory in the git repo, it is only created when the real UI assets are built and copied there. I created #3698, please try updating promscale to use that branch & see if it fixes your issue.

**Comment by wpcarro** [comment]
Thanks for the quick response. Calling `go mod vendor` is now working as expected :)
