### ISSUE TITLE
jaeger-query UI suggestions

### ISSUE THREAD

**Issue by Dieterbe** [jaegertracing/jaeger#372]
would be nice to have a litle `(?)` icon for some fields with more information, in particular i'ld like to know:
* custom time range -> what timezone is this in? same as browser, same as server? can it confirm? option to specify TZ would be nice too
* tags: what format exactly? do some characters need escaping? which? how? can we do pattern searches or only literal strings? using what pattern syntax?
* tags: how to specify multiple with an AND condition? i saw in the jaeger-query source code that the handler is passed multiple tag form fields, but through the ui I think you can only pass one, and whatever you put in there (space separated or common separated) is sent as 1 tag field AFAICT ? possible to do OR and/or nested expressions? does it matter if the tag is found the main span or a client span? (doesn't look like it)

**Comment by rbtcollins** [comment]
I've just audited the code. Multiple tags given e.g. `http.status_code:400|http.method:PATCH` in the UI will result in an AND query in cassandra. https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/spanstore/reader.go#L295

I think it would be good to do two things:
1. add an OR semantic, because it would be very useful.
2. Change the ui so that | means OR, and & means AND. Because that matches other languages developers use :). Even the sample query the UI shows today is actually never going to return anything due to the current AND semantics.

**Comment by Dieterbe** [comment]
@tiffon FYI ^^ (sorry maybe i should have put this in the jaeger-ui repo). i have a better understanding of the limitations now (e.g. no tag pattern search with cassandra) but the points remain that the UI could clarify a lot of these questions for new users

**Comment by tiffon** [comment]
Thanks @Dieterbe... I was looking this over yesterday, it's great feedback :+1: 

We've added the `ui` label to track this more easily. I might end up creating tickets in the Jaeger UI repo or moving this ticket there...

**Comment by yurishkuro** [comment]
* Moved time zone suggestion to https://github.com/jaegertracing/jaeger-ui/issues/154
* tag format is now explained (https://github.com/jaegertracing/jaeger-ui/issues/145)
* OR of tags is not supported by the backend. We can create a new issue for that, but this is not a high priority.
