### ISSUE TITLE
[Feature]: Missing Windows Release For 1.37.0

### ISSUE THREAD

**Issue by jadanah** [jaegertracing/jaeger#3871]
### Requirement

Windows binaries for 1.37.0

### Problem

The windows binaries are missing from the 1.37.0 release https://github.com/jaegertracing/jaeger/releases/tag/v1.37.0

**Comment by albertteoh** [comment]
I believe this is fixed by https://github.com/jaegertracing/jaeger/pull/3854, however it looks like GH Actions runs against the tag, so it wouldn't pickup that fix even if we could re-run the release jobs. The cleanest option I can think of is to tag a new (bugfix) release, but there may be better alternatives that I'm not aware of.

What do you think @yurishkuro?

**Comment by yurishkuro** [comment]
I would just wait for the next release, but if necessary we could do a patch release.

**Comment by albertteoh** [comment]
I'll close this issue for now in favour of waiting for the next major version release in 2 weeks, which should contain the the windows release. If an urgent release is necessary, we can reopen.
