### ISSUE TITLE
[Feature]: Elasticsearch config details can taken by an env variable through file inside pod filesystem. 

### ISSUE THREAD

**Issue by crombus** [jaegertracing/jaeger#3924]
### Requirement

Elasticsearch config details can taken by an env variable through file inside pod filesystem. For now we have to pass through configmap.

### Problem

Integrating with vault which injector to inject passwords inside the podfilesystem.

### Proposal

Create env variable for elastic in jaeger which takes password from file. Similarly to keycloak.

### Open questions

Any other way we can do so, Please suggest for the time being.

**Comment by yurishkuro** [comment]
Would it also require watching the file for password changes?

**Comment by crombus** [comment]
yes, for rotating passwords.

**Comment by haanhvu** [comment]
I'll work on this

**Comment by haanhvu** [comment]
@yurishkuro Could you point me to which files I need to change to implement this? For now I can see the ES config is here: https://github.com/jaegertracing/jaeger/blob/main/pkg/es/config/config.go

**Comment by yurishkuro** [comment]
There are several parts to this (best done in different PRs):

1. Refactor file system watchers into one module. Right now two modules in Jaeger support file reloads: `cmd/query/app/static_handler.go` and `pkg/config/tlscfg/cert_watcher.go`. They both rely on 3rd party `fsnotify` module, however the latter is much more involved and can deal with symlinks and whole directories being replaced, which was reported several time as a problem for the original version of `cert_watcher`. So I would like to move this to a shared functionality (into `pkg/fswatcher` module, which currently doesn't do much), and refactor the other two places to use it.
2. Once that shared watcher is available, use it to add a new option to ES storage to read the password from a file (as well as token-file, which is already supported).
3. Lastly, we need to actually be able to support changing password/token on the fly. IIRC all auth settings are done at the start when ES client is initialized, so this requires a bit of research what it would take if those arguments need to be modified - is the code structured such that ES client can be easily swapped?

**Comment by yurishkuro** [comment]
To provide more details about the proposal.

Step 1 is to move the file & directory watching logic from `tlscfg` to `pkg/fswatcher` completely, and expose a much simpler API to the other packages, not the low-level API of the current fswatcher. The API I am thinking of is the following:
```go
type FSWatcher interface {
  WatchFiles(paths []string, onChange func())
  Close()
}
```

The implementation can do this:
  * load file contents and store their checksums
  * register watchers with fsnotifier for both the files and their directoties (as currently done in `tlscfg`)
  * upon change notification, load files and verify that their checksums changed. If not - skip.
  * if checksums changed, invoke the `onChange` callback

Internally the implementation may use one or several fsnotify watchers, whichever is easier. The main requirement is that if I call `WatchFiles` several times, I should be able to provide different callbacks, because as you can see in `tlscfg` different certificates are handled differently (some loaded in pairs):
```go
fsw.WatchFiles([]string{"a", "b"}, func() { print("a or b") }
fsw.WatchFiles([]string{"c"}, func() { print("c") }
```

So my concrete proposal is:
  1. (PR1) implement the above in `pkg/fswatcher` as a new struct, by porting some of the implementation from `tlscfg` package, with unit tests.
  2. (PR2) refactor `tlscfg` to use the new watcher from PR1
  3. (PR3) refactor `static_handler.go` similar to (PR2)
  4. come back to PR #4235 and do it similar to PR2/PR3.

**Comment by haanhvu** [comment]
> The API I am thinking of is the following:
> 
> ```go
> type FSWatcher interface {
>   WatchFiles(paths []string, onChange func())
>   Close()
> }
> ```

@yurishkuro I agree, with a small addition:
```go
type FSWatcher interface {
  WatchFiles(paths []string, loadFiles func(), onChange func())
  Close()
}
```

Because I see `tlscfg` and `static_handler.go` (and potentially any packages that use `FSWatcher` in the future) load files and store file contents differently.

Does this make sense?

**Comment by yurishkuro** [comment]
No, I don't se much point in loadFiles(), because the user of this watcher already knows when & how to do the initial load, so what additional value does the watcher provide for that? With onChange the value is clear because the user does not know _when_ the files changed and need to be reloaded.

**Comment by yurishkuro** [comment]
To give an example, say the user of watcher has two groups of files. It would do something like this:
```go
loadGroupA()
watcher.WatchFiles(filesGroupA, loadGroupA)

loadGroupB()
watcher.WatchFiles(filesGroupB, loadGroupB)
```
