### ISSUE TITLE
[Feature]: Migrate to go 1.20 

### ISSUE THREAD

**Issue by scalalang2** [jaegertracing/jaeger#4202]
### Requirement

[Go 1.20 officially released today](https://tip.golang.org/doc/go1.20)
There's improvements on the garbage collector. It informs that its overall performace improves by up to 2% and reduces memory overheads. I guess that migrating to go 1.20 will provides improved performance, bug fixes, security enhancements and etc.

### Problem

There's no problem on Jaeger.
This proposal only include a simple suggestion.

Thanks.

### Proposal

Migrate to go runtime 1.20.

**Comment by yurishkuro** [comment]
Files to change:
```
$ grep -r 1.19 .
./go.mod:3:go 1.19
./docker/Makefile:4:GOLANG_IMAGE := golang:1.19-alpine
./.golangci.yml:2:  go: '1.19'
./.golangci.yml:30:    go: "1.19"
./.github/workflows/fossa.yml:28:          go-version: 1.19.x
./.github/workflows/ci-release.yml:34:        go-version: 1.19.x
./.github/workflows/ci-unit-tests.yml:33:        go-version: 1.19.x
./.github/workflows/ci-docker-build.yml:34:        go-version: 1.19.x
./.github/workflows/ci-build-binaries.yml:51:        go-version: 1.19.x
./.github/workflows/ci-crossdock.yml:34:        go-version: 1.19.x
./.github/workflows/ci-elasticsearch.yml:46:        go-version: 1.19.x
./.github/workflows/ci-grpc-badger.yml:27:        go-version: 1.19.x
./.github/workflows/ci-hotrod.yml:33:        go-version: 1.19.x
./.github/workflows/ci-protogen-tests.yml:29:        go-version: 1.19.x
./.github/workflows/ci-all-in-one-build.yml:33:        go-version: 1.19.x
./.github/workflows/ci-cassandra.yml:39:        go-version: 1.19.x
./.github/workflows/ci-opensearch.yml:43:        go-version: 1.19.x
./.github/workflows/ci-kafka.yml:27:        go-version: 1.19.x
```

**Comment by SaarthakMaini** [comment]
PR for the issue has already been made and would be merged during the next Release Cycle.

**Comment by scalalang2** [comment]
👍

**Comment by mx-psi** [comment]
I opened #4328 to suggest partially reverting the changes on #4206 so that Jaeger remains compatible with Go 1.19 as a library. This would help the OpenTelemetry Collector project, which [aims to be compatible with all officially supported Go versions](https://github.com/open-telemetry/opentelemetry-collector#compatibility).

Note that my PR **only changes the go.mod file**: binaries would be built with Go 1.20 which I think would fulfill the goals that @scalalang2 talks about in this issue.

Please consider my PR! :)
