### ISSUE TITLE
[Bug]: SPM - Error rate % not showing 4xx client errors.

### ISSUE THREAD

**Issue by mayank-rocketml** [jaegertracing/jaeger#4400]
### What happened?

4xx errors are not getting displayed in Error rate % (SPM - Monitor Tab).

The reason is that the HTTP status codes in the 4xx range span status is being left unset in case of SpanKind.SERVER by Span Metrics processor (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12753).

I think this is a bug. 
The Error rate % tab should also consider displaying data for 4xx errors (span_kind="SPAN_KIND_SERVER", status_code="STATUS_CODE_UNSET")

### Steps to reproduce

Generate 4xx errors from an application. Traces will appear in Jaeger but the Monitor tab will not show it as an error.

### Expected behavior

Error rate % graph in Monitor tab should consider displaying data for 4xx errors.

**Comment by juferreira** [comment]
Hello. Any update for that? 
I have the same problem.

**Comment by albertteoh** [comment]
SPM tab supports querying metrics on span kind; if you're capturing client spans, you should be able to see these error metrics in SPM.

Otherwise, if we're not collecting client spans, could we use collector processors (e.g. [attributesprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor)) to set `status_code="STATUS_CODE_ERROR"` if the [http.response.status_code](https://opentelemetry.io/docs/specs/semconv/attributes-registry/http/) is 4xx?

I think we should try to avoid modifying SPM functionality to support error edge cases where `status_code != "STATUS_CODE_ERROR"`.

**Comment by juferreira** [comment]
I'm using the last version of helm chart (0.73.1), but I realised that the default version of All-In-One deployment on this chart are 1.51.0. I updated the tag version of the deployment to 1.53.0 and now I have the filter Span Kind and all the erros available. 
`
        allInOne:
          tag: 1.53.0
          args: 
          - --prometheus.query.support-spanmetrics-connector=true
          - --query.enable-tracing=true
          enabled: true
          extraEnv: 
            - name: METRICS_STORAGE_TYPE
              value: prometheus
            - name: PROMETHEUS_SERVER_URL
              value: http://prometheus.observability.svc.cluster.local:9090
            - name: PROMETHEUS_QUERY_NORMALIZE_CALLS
              value: 'true'
            - name: PROMETHEUS_QUERY_NORMALIZE_DURATION
              value: 'true'
`

And if I search for traces (in the Search tab) using the `http.status_code=400` Tag, I can also see all logs with status code 400.

I hope this can help.

**Comment by jkowall** [comment]
Per @albertteoh I do not think we should support this edge case in SPM. 
 
> I think we should try to avoid modifying SPM functionality to support error edge cases where `status_code != "STATUS_CODE_ERROR"`.
