### ISSUE TITLE
[spm] Change README to use tracegen

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4503]
The [README](https://github.com/jaegertracing/jaeger/blob/main/docker-compose/monitor/README.md#setup) currently suggests running `./otlp_exporter_example.py`, why is that?  Can we instead provide an example command of running the `tracegen`?  Instead of saying "[run] a number of times", tracegen can have an exact command line that runs for a specified period of time with given throughput, which seems more useful for SPM. And IIRC we already use it in the docker-compose file, so I would retire the python script altogether.

**Comment by albertteoh** [comment]
I introduced [microsim](https://github.com/jaegertracing/jaeger/blob/main/docker-compose/monitor/docker-compose.yml#L30) for this purpose of generating traces. I used microsim because it has a relatively complex trace structure with multiple "services" having varying latencies, while also generating a continuous stream of span traffic to give meaningful visualizations of requests and durations.

`./otlp_exporter_example.py` served two purposes:
1. A very simple example application to demonstrate OTEL instrumentation, in one file. Python is a popular and approachable language.
2. An interactive way to sending traces one at a time, with immediate feedback in Jaeger UI.

If we feel `./otlp_exporter_example.py` is not useful, I would rather remove it altogether than replace it with `tracegen`, given `microsim` serves the use case of generating a meaningful stream of traces, unless if there's another use case?

**Comment by yurishkuro** [comment]
@albertteoh the README currently talks about two different modes, one is using docker compose that runs microsim, and the other running a python script, which apparently only generates a single trace. I think that script can be replaced by running tracegen.

**Comment by yurishkuro** [comment]
btw, #4747 is why I prefer to remove python script. Unnecessary maintenance.

**Comment by albertteoh** [comment]
> btw, #4747 is why I prefer to remove python script. Unnecessary maintenance.

Yup, that's a fair point. I'll have a look into using tracegen.
