### ISSUE TITLE
With ScyllaDB (and likely Cassandra too), increasing TTL leads to large numbers of sstables

### ISSUE THREAD

**Issue by avikivity** [jaegertracing/jaeger#4561]
### What happened?

A ScyllaDB user ran with the Cassandra backend, but increased the TTL to 30 days.

Some tables use TimeWindowCompactionStrategy, which segregate time series into separate time windows. They use a 1 hour window.

A TTL of 30 days divided by 1 hour leads to 720 windows. With many such tables, this causes tens of thousands of SSTables, and hundreds of thousands of files (since each SSTable is composed of seven files). This stresses the server.

The Cassandra [documentation](https://cassandra.apache.org/doc/latest/cassandra/operating/compaction/twcs.html) recommends:

> Ideally, operators should select a compaction_window_unit and compaction_window_size pair that produces approximately 20-30 windows - if writing with a 90 day TTL, for example, a 3 Day window would be a reasonable choice ('compaction_window_unit':'DAYS','compaction_window_size':3).

### Steps to reproduce

1. Run using Cassandra or ScyllaDB with 30-day TTL
2. Insert data for 30 days
3. Observe hundreds of thousands of files

### Expected behavior

Fewer files.

### Additional context

Recommendation: set the window size to be (TTL / 10) or so.

### Jaeger backend version

unknown - not my setup

### Stogage backend

Cassandra (but using ScyllaDB)

**Comment by yurishkuro** [comment]
You can alter tables in cqlsh to set different compaction windows.

Currently this is not configurable in the schema script https://github.com/jaegertracing/jaeger/blob/1b28b239f3c561d4162287b66511affcbbe1ffa4/plugin/storage/cassandra/schema/v004.cql.tmpl#L69-L73

**Comment by avikivity** [comment]
Yes, but it would be better if the default was set up correctly in the first place.

**Comment by yurishkuro** [comment]
So the proposal would be

* change hardcoded window size like this one https://github.com/jaegertracing/jaeger/blob/a15f3a3e7b4aad92ad8c688b43f359f4b12143b2/plugin/storage/cassandra/schema/v004.cql.tmpl#L69 to be a parameter
* allow overriding that parameter in plugin/storage/cassandra/schema/create.sh, and if not provided as input compute it from the total TTL so that it results in 30 intervals. For TTL=30d this means compaction window of 1 day, but for TTL=3d the window will be about 3hrs

**Comment by avikivity** [comment]
Looks great, thanks.
