### ISSUE TITLE
Implement N-1 support policy for Go versions

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4653]
Follow up to https://github.com/jaegertracing/jaeger/issues/4329.

* [ ] implement a linter check `scripts/check-go-version.sh` that verifies that all our build scripts are using the same Go version N, but go.mod is N-1. This includes GH actions, Alpine images, etc.
* [x] implement a convenience script `scripts/update-go-version.sh` that updates those scripts to another version, to make these upgrades easier in the future (see #4652 for reference). It should also bump go.mod to N-1.
* [x] add a section to README (similar to `Version Compatibility Guarantees`) explaining the policy. For reference: https://github.com/open-telemetry/opentelemetry-collector#compatibility

Since Go 1.21 is out, this is an opportunity to test this new process.

**Comment by shubmjagtap** [comment]
Hi @yurishkuro ,

in task 1 : "verifies that all our build scripts are using the same Go version N"

1.how do i find those build scripts from such large code base ? 
2.Are these {build scripts} present in "script" folder as ".sh" files?

**Comment by wasup-yash** [comment]
hey @yurishkuro what is the estimated/expected time limit if any for these issues to get resolved/implemented?

**Comment by Mayhul-Jindal** [comment]
Hey @yurishkuro as I was trying to setup the project I encountered this issue
![image](https://github.com/jaegertracing/jaeger/assets/95216160/d1728cfd-5fbd-4790-b66b-7202042926a9)
I have already tried removing the `go.sum` and then regenerated it using `go mod tidy` but still if gave me the same error. I am new to contributing and stuff, can you suggest me what should I do next ?

**Comment by Mayhul-Jindal** [comment]
> Hey @yurishkuro as I was trying to setup the project I encountered this issue ![image](https://user-images.githubusercontent.com/95216160/260243306-d1728cfd-5fbd-4790-b66b-7202042926a9.png) I have already tried removing the `go.sum` and then regenerated it using `go mod tidy` but still if gave me the same error. I am new to contributing and stuff, can you suggest me what should I do next ?

Continuing this, I faced issue in running `make lint` because  `github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.1` was not able to install correctly. When I installed its updated version ` go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.1` everything seems to work fine now. Should the version be changed to `1.54.1` ?
![image](https://github.com/jaegertracing/jaeger/assets/95216160/1e83a6cf-865e-437a-876d-2979a7bb4534)

**Comment by albertteoh** [comment]
> Should the version be changed to 1.54.1 ?

If we upgrade golangci-lint, we'll be subject to the problem described in: https://github.com/golangci/golangci-lint/issues/3906, where a large number of depguard lint errors appear.

We'll need to understand why those linting errors are appearing and what actions need to be taken to address them, or if it's better to stick with the current version until that problem is ironed out in a later version.

FWIW, I didn't have any issues installing 1.52.1.
