### ISSUE TITLE
[Feature]: update python to python3

### ISSUE THREAD

**Issue by shubmjagtap** [jaegertracing/jaeger#4673]
### Requirement

I want to update the Python version used in Jaeger's build scripts.

so that
contributors can use the latest version of Python (Python 3) without encountering compatibility issues and errors during the build process. This will improve the overall development experience and ensure that the contribution process is smoother for all contributors.

### Problem

**Problem:**

Jaeger's current build scripts utilize the "python" command instead of "python3," causing obstacles when contributors with Python 3 try to execute the "make fmt" command. This leads to errors and confusion, disrupting the smooth contribution process and delaying code formatting.

**Impact:**

The use of "python" instead of "python3" in Jaeger's build scripts prevents contributors with Python 3 from running the "make fmt" command successfully. This discrepancy causes errors and hampers the timely execution of code formatting tasks, affecting the overall contribution workflow.

**for eg**

when i run `make fmt` before submitting PR according to contribution guidelines i get following output 

`
./scripts/import-order-cleanup.sh inplace
./scripts/import-order-cleanup.sh: line 5: python: command not found
make: *** [Makefile:154: fmt] Error 127`

to solve this i changed to older version of python used in **"./scripts/import-order-cleanup.sh"** to python3 

```
#!/bin/bash

set -e

python scripts/import-order-cleanup.py -o $1 -t $(git ls-files "*\.go" | \
    grep -v \
        -e thrift-gen \
        -e swagger-gen \
        -e thrift-0.9.2 \
        -e proto-gen \
        -e model.pb.go \
        -e model_test.pb.go \
        -e storage_test.pb.go
)
```
above is updated to following 

```
#!/bin/bash

set -e

python3 scripts/import-order-cleanup.py -o $1 -t $(git ls-files "*\.go" | \
    grep -v \
        -e thrift-gen \
        -e swagger-gen \
        -e thrift-0.9.2 \
        -e proto-gen \
        -e model.pb.go \
        -e model_test.pb.go \
        -e storage_test.pb.go
)

```

i suggest to do it for every script file which is using older version of python

for example 
```

scripts/import-order-cleanup.sh:
  4  
  5: python scripts/import-order-cleanup.py -o $1 -t $(git ls-files "*\.go" | \
  6      grep -v \

scripts/updateLicenses.sh:
  4  
  5: python scripts/updateLicense.py $(git ls-files "*\.go" | \
  6      grep -v \

```

### Proposal

i suggest to do it for every script file which is using older version of python

for example 
```

scripts/import-order-cleanup.sh:
  4  
  5: python scripts/import-order-cleanup.py -o $1 -t $(git ls-files "*\.go" | \
  6      grep -v \

scripts/updateLicenses.sh:
  4  
  5: python scripts/updateLicense.py $(git ls-files "*\.go" | \
  6      grep -v \

```

**Comment by albertteoh** [comment]
> An alternative is to `alias python=python3`, which I thought was a common practice.

Unfortunately, it turns out aliases aren't expand in bash scripts, and so aliases won't work.

However, it would also be nice to maintain backward compatibility with `python`.

With that, instead of forcing  users to switch to python3, what do folks think about writing a script that prefers `python3` and falls back to `python` if `python3` doesn't exist, which other scripts can invoke to get the correct python command?

e.g.

```shell
#!/bin/bash

cmd=""

if command -v python3 &> /dev/null
then
    echo "python3"
elif command -v python &> /dev/null
then
    echo "python"
else
    echo "please install python"
    exit 1
fi
```

and usage would look like:
```shell
cmd=$(scripts/check-python.sh)

$cmd scripts/updateLicense.py $(git ls-files "*\.go" | \
...
```

**Comment by yurishkuro** [comment]
I don't see what the problem is. If someone has python installed on a machine, the "python" command usually works, regardless of which version it calls.

**Comment by albertteoh** [comment]
> I don't see what the problem is. If someone has python installed on a machine, the "python" command usually works, regardless of which version it calls.

My current VM is running [Ubuntu 22.04.3 LTS](https://releases.ubuntu.com/jammy), and does not have `python` installed:
```
~ $ python
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
```

I can  `alias python=python3`:
```
~ $ python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
``` 

but this won't work if executing python scripts with the `python` alias because aliases aren't expanded in shell scripts.

```shell
$ make fmt
./scripts/import-order-cleanup.sh inplace
./scripts/import-order-cleanup.sh: line 5: python: command not found
```

There _are ways_ of installing `python` to point to `python3` but it adds unnecessary friction to contributors, IMO, especially when python 2 has been [sunsetted for over 3.5 years](https://www.python.org/doc/sunset-python-2/#:~:text=The%20sunset%20date%20has%20now,when%20we%20released%20Python%202.7.).

I think a cleaner alternative is to be explicit about what python version should be used via a shebang within the python script itself; as recommended in this [SO answer](https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take).

[PEP 394](https://peps.python.org/pep-0394/#recommendation) also recommends:
> When packaging third party Python scripts, distributors are encouraged to change less specific shebangs to more specific ones.
> ...
> - Changing python shebangs to python3 when Python 3.x is supported.
> - Changing python shebangs to python2 when Python 3.x is not yet supported.
> - Changing python3 shebangs to python3.8 if the software is built with Python 3.8.

From above, I propose being opinionated about the version we use in all our python scripts via the shebang:

```shell
#!/usr/bin/env python3
```

... and shell scripts execute python scripts as plain executables (after we `chmod 755` on the python scripts), for example:

```shell
./scripts/import-order-cleanup.py
```

If we agree, I can submit a PR based on the above proposal.

**Comment by yurishkuro** [comment]
Sounds good
