### ISSUE TITLE
Docker compose for deployment of individual components

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#469]
See #466 for context and https://github.com/jaegertracing/jaeger-kubernetes/blob/master/production/jaeger-production-template.yml for reference

This should be done in a separate repository, like there is for Kubernetes and OpenShift.

**Comment by jpkrohling** [comment]
See #306 for a starting point.

**Comment by ishanjain28** [comment]
Hi, I'd like to take this up if it is still available.

**Comment by allieoop** [comment]
Note: `jaeger-kubernetes/production/jaeger-production-template.yml` was renamed to `jaeger-kubernetes/production/cassandra.yml` (see https://github.com/jaegertracing/jaeger-kubernetes/commit/f930d0ab75bd042bdcc539acefd81f7fc9992016#diff-0b3583916142302afe2c114d88c1f7c1) - Issue description with this reference needs to be updated.

**Comment by allieoop** [comment]
@ishanjain28 are you interested in working together on this?

I was just wondering what name we should give to the new repo. Maybe something like `jaeger-compose`?

**Comment by ishanjain28** [comment]
@allieoop Yeah, Sure. `jaeger-compose` sounds good to me.

**Comment by pavolloffay** [comment]
@ishanjain28 see #493

**Comment by allieoop** [comment]
If I'm understanding this correctly, it sounds like the goal of this issue is to move the docker compose file into a separate repo so that it can be used to support multiple storages. I see the following question asked in Issue 493 (https://github.com/jaegertracing/jaeger/pull/493#issuecomment-339730092): do we want to move the docker compose file into a separate repo? But I don't see any further discussion. If anyone has any thoughts on why this should be done, it would be helpful to discuss it here in the issue to move the compose file out of this repo and into a new one, like what storages do we want to support that we aren't currently supporting or anything else?

**Comment by pavolloffay** [comment]
>  it sounds like the goal of this issue is to move the docker compose file into a separate repo so that it can be used to support multiple storages.

Compose file can be here on in a different repo and still support different storages.

I think it's easier to have it directly here because:
*  it's used in crossdock - it's automatically tested
* can more quickly adopt new changes

cc @jpkrohling @yurishkuro

**Comment by pavolloffay** [comment]
We can reuse this compose file in different jaeger repositories to run xdock tests:

```bash
docker-compose -f https://github.com/jaegertracing/jaeger/master/compose.yml -f $(XDOCK_YAML) run crossdock 
```

**Comment by jpkrohling** [comment]
I'm not really familiar with how the cross-dock setup works, but `docker-compose` is an orchestration tool like OpenShift or Kubernetes. If the right place for the `compose.yml` file is here on this repo, then we might consider moving OpenShift's and Kubernetes' here as well.

**Comment by pavolloffay** [comment]
done in https://github.com/jaegertracing/jaeger/pull/493. 

I will open next issue for further improvements.
