### ISSUE TITLE
Investigate why code coverage badge in README shows such a low number

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5099]
## Badge

<img width="152" alt="image" src="https://github.com/jaegertracing/jaeger/assets/3523016/78f67c66-4999-4267-9458-a1dfd213ac7b">

## Codecov

<img width="491" alt="image" src="https://github.com/jaegertracing/jaeger/assets/3523016/b52b839e-894c-492f-b693-a788f046dc85">

## Pull request

Meanwhile, in the [pull requests](https://github.com/jaegertracing/jaeger/pull/5098#issuecomment-1890998345)

<img width="695" alt="image" src="https://github.com/jaegertracing/jaeger/assets/3523016/8d2a0c2f-db02-4603-92a4-2d8736835821">

**Comment by yurishkuro** [comment]
Possible explanation:

<img width="170" alt="image" src="https://github.com/jaegertracing/jaeger/assets/3523016/c8cbf9b4-e50a-4624-928c-b975fd6317e9">

this points to a commit `f313486` which is not even on the main branch, but a work in progress commit in another branch:

<img width="479" alt="image" style="border-style: double" src="https://github.com/jaegertracing/jaeger/assets/3523016/f845a47c-f9a6-47a1-af19-0cbc97e59630">

**Comment by Pushkarm029** [comment]
Yes, we see low code coverage due to a work-in-progress branch because there are a lot of [indirect changes](https://app.codecov.io/gh/jaegertracing/jaeger/commit/f3134867463b301b90fdd21b658985116a165d11/indirect-changes) that significantly drops the codecov percentage.

Possible solution:
- instead of showing the main branch codecov, we show a release branch coverage in the readme.
- & then write a GH Action to change the old release to the new release in the readme when a release comes.

**Comment by chirag-ghosh** [comment]
The badge now shows correct output: 
![image](https://github.com/jaegertracing/jaeger/assets/75582834/d49c80f3-450a-4519-955c-59262baef240)

Did anything change?

**Comment by Pushkarm029** [comment]
@chirag-ghosh, This is showing correctly now because the latest commit has 95% code coverage. It will break again if you make some significant code changes in an unrelated branch. 

The primary purpose of this ticket is to investigate why codecov includes unrelated branch commits in the main. You can research more about it [here](https://app.codecov.io/gh/jaegertracing/jaeger).

**Comment by jkowall** [comment]
This seems to be resolved now, as the trends on https://app.codecov.io/gh/jaegertracing/jaeger look healthy.
