### ISSUE TITLE
[Feature]: can we upgrade the base image of jaeger-query?

### ISSUE THREAD

**Issue by kevincantu** [jaegertracing/jaeger#5450]
### Requirement

Patches for all the thingsss.

### Problem

I see `jaegertracing/jaeger-query:latest` is still based on Alpine 3.16.9, and 3.16 is about to be EOL ([ref](https://alpinelinux.org/releases/)).

**Comment by yurishkuro** [comment]
Instead of doing this manually, we should have dependabot do the upgrades automatically. However, I see that the image version is currently hardcoded in the Makefile, which dependabot probably won't be able to handle. it would be great to find a way to keep the version defined directly in some Dockerfile.

```
$ grx alpine .
./docker/Makefile:2:ROOT_IMAGE ?= alpine:3.16
./docker/Makefile:4:GOLANG_IMAGE := golang:1.22-alpine
./docker/Makefile:7:BASE_IMAGE ?= $(DOCKER_REGISTRY)/baseimg_alpine:latest
./docker/Makefile:8:DEBUG_IMAGE ?= $(DOCKER_REGISTRY)/debugimg_alpine:latest
./scripts/build-upload-a-docker-image.sh:19:		base_debug_img_arg="--build-arg base_image=localhost:5000/baseimg_alpine:latest --build-arg debug_image=localhost:5000/debugimg_alpine:latest "
```

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/jaeger/pull/5454/files#r1606261791

**Comment by yurishkuro** [comment]
dependabot is now upgrading alpine: #5469 🎉
