### ISSUE TITLE
when trace id is invalid, jaeger-ui send this request forever

### ISSUE THREAD

**Issue by meilihao** [jaegertracing/jaeger#556]
jaeger verison: 3136216e0636e67e39c6815b909f0cf9e0888884
jaeger-ui version : 27c3d58e224f0ff78a4ce0ba4622d47ec4bffa7c

```sh
$ query 2>&1 > query.log --query.static-files=jaeger-ui/build/ --span-storage.type=elasticsearch --es.server-urls="${ESServerUrls}"
```

![_ _20171124184124](https://user-images.githubusercontent.com/4382586/33207051-3017cca8-d147-11e7-9bfa-6eefbc400e69.png)

**Comment by yurishkuro** [comment]
cc @tiffon

**Comment by tiffon** [comment]
That's pretty odd. I would expect an invalid ID to have a 404 response, but these are 200. 

Does the response have any data? Is there a trace, and if so what is the traceID?

Thanks for reporting this.

**Comment by yurishkuro** [comment]
When I access URL with invalid trace ID I am getting this

![image](https://user-images.githubusercontent.com/3523016/33242836-e4535e14-d2a8-11e7-9d53-7f7799fbac2f.png)

This happens with Cassandra and in-memory backend. Maybe the issue is with ES storage not returning NotFound.

The UI display about could be worded a bit better, "something that doesn't exist" is actually the trace, and the "bad JSON" error is misleading.

**Comment by tiffon** [comment]
Improving the error messages is something I want to look into. I'll create a ticket in jaeger-ui for it if there isn't one, already.

**Comment by tiffon** [comment]
Will also, of course, address this issue, specifically.

**Comment by meilihao** [comment]
![_ _20171127095307](https://user-images.githubusercontent.com/4382586/33247416-f3d6ce42-d358-11e7-9a0d-fe0e860e2e3c.png)

respone:
```json
{"data":[{"traceID":"","spans":[],"processes":{},"warnings":null}],"total":0,"limit":0,"offset":0,"errors":null}
```

**Comment by yurishkuro** [comment]
@black-adder I see this code in ES spanstore

```go
// GetTrace takes a traceID and returns a Trace associated with that traceID
func (s *SpanReader) GetTrace(traceID model.TraceID) (*model.Trace, error) {
	currentTime := time.Now()
	traces, err := s.multiRead([]string{traceID.String()}, currentTime.Add(-s.maxLookback), currentTime)
	if err != nil {
		return nil, err
	}
	if len(traces) == 0 {
		return nil, errNoTraces
	}
	return traces[0], nil
}
```

There are two problems here. First, when no traces are found the error should be `spanstore.ErrTraceNotFound`, instead of the private error. But it may not help either because in the multiread function there's this code

```go
	var traces []*model.Trace
	for _, result := range results.Responses {
		if result.Hits == nil {
			return nil, errNilHits
		}
```

If I read it correctly, the method would return `errNilHits`, so the `len(traces) == 0` logic above would never even be run.

**Comment by NeoCN** [comment]
@yurishkuro the flowing multiread function code snippet
```golang
	var traces []*model.Trace
	for _, result := range results.Responses {
		if result.Hits == nil {
			return nil, errNilHits
		}
		spans, err := s.collectSpans(result.Hits.Hits)
		if err != nil {
			return nil, err
		}
		traces = append(traces, &model.Trace{Spans: spans})
	}
	return traces, nil
```

when the traceId is invalid or not in the es store, got result 
```
[]*model.Trace{
    &model.Trace{
        Spans: {
        },
        Warnings: nil,
    },
}
```

this results that `len(traces) == 0` will not trigger, and then no `errNoTraces ` is returned.

when `len(result.Hits.Hits) == 0`,  `collectSpans` will return `[]*model.Span` with zero length and no error.

I just make a pull request #597 which check `len(result.Hits.Hits)`, when `len(result.Hits.Hits) == 0` skip `collectSpans`

**Comment by yurishkuro** [comment]
#601 and the UI fix https://github.com/jaegertracing/jaeger-ui/issues/128 resolve this.
