### ISSUE TITLE
Add missing file to mocks generation

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5818]
We have `generate-mocks` make target that is supposed to regenerate all mocks. I just bumped into a manually generated file that is not included in that auto-generation: ./plugin/storage/grpc/mocks/PluginCapabilities.go

The goal is to add it to mockery config and commit a new version.

**Comment by Zen-cronic** [comment]
Based on the current [config](https://github.com/jaegertracing/jaeger/blob/0da1609a1755a5a40363208e71adbc5b45f24e8b/.mockery.yaml#L45), we can change the package path to the `/grpc/shared`. Because the interface [`PluginCapabilities`](https://github.com/jaegertracing/jaeger/blob/f250716cc0a1131dba46986ac4455eb43c364a15/plugin/storage/grpc/shared/interface.go#L41) is in the `shared` sub-directory. 

This is different from the `storage/kafka` where the mocked interfaces are in the file residing in the [root](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/kafka/marshaller.go) of package. 

- kafka storage related interfaces: `plugin/storage/kafka/marshaller.go` 
- current grpc storage related interfaces: `plugin/storage/grpc/shared/interface.go` (in the `shared` subdir)

Possible solution in `.mockery.yaml`:
```bash
# github.com/jaegertracing/jaeger/plugin/storage/grpc:
  github.com/jaegertracing/jaeger/plugin/storage/grpc/shared:
    interfaces:
      PluginCapabilities:
```
But there's a caveat: The auto-generated mock file will be stored in the `/grpc/shared/mocks` subdir instead of the root `/grpc/mocks`.

**Comment by yurishkuro** [comment]
@Zen-cronic I think it's fine if the mock moves to a different dir, it's not used that broadly anyway, so you can fix the caller.
```
$ rg mocks.PluginCapabilities
plugin/storage/grpc/factory_test.go
92:		Capabilities: new(mocks.PluginCapabilities),
179:	capabilities := f.services.Capabilities.(*mocks.PluginCapabilities)
203:	capabilities := f.services.Capabilities.(*mocks.PluginCapabilities)
225:	capabilities := f.services.Capabilities.(*mocks.PluginCapabilities)
286:	capabilities := f.services.Capabilities.(*mocks.PluginCapabilities)
```

**Comment by Zen-cronic** [comment]
@yurishkuro Gotcha. I'll remove the manually generated file, too.
