### ISSUE TITLE
[Bug]: v004-go-tmpl.cql.tmpl  error

### ISSUE THREAD

**Issue by Zherphy** [jaegertracing/jaeger#6415]
### What happened?

![Image](https://github.com/user-attachments/assets/b6c99fd0-4ba6-4716-a9c2-c585e3010049)
When i use docker to run jaegertracing/jaeger-cassandra-schema:latest, some error occurred。

I checked v004-go-tmpl.cql.tmpl， find something wrong.

### Steps to reproduce

docker run -e CQLSH_HOST=[] -e CQLSH_PORT=[] -e MODE=test -e CASSANDRA_USERNAME=[] -e CASSANDRA_PASSWORD=[] -e KEYSPACE=[] jaegertracing/jaeger-cassandra-schema:latest

### Expected behavior

run successed

### Relevant log output

```shell

```

### Screenshot

![Image](https://github.com/user-attachments/assets/6613992b-21bd-42ff-84a1-84b1224eda21)

### Jaeger backend version

jaegertracing/jaeger-cassandra-schema:1.64.0

### Deployment configs

```shell

```

**Comment by yurishkuro** [comment]
cc @akstron

**Comment by yurishkuro** [comment]
@Zherphy 

When you say `jaegertracing/jaeger-cassandra-schema:latest` this doesn't tell me anything because `latest` may pick to any random version cached in your local registry. Please run a concrete version.

The `go-tmpl` file is not meant to be used with this script, I don't know how you are able to get the error message, your repro command will not cause it. This command works fine: `docker run -e CASSANDRA_PASSWORD=cassandra -e CASSANDRA_USERNAME=cassandra --network host -e CQLSH_HOST=localhost -e MODE=test jaegertracing/jaeger-cassandra-schema:1.64.0`
