### ISSUE TITLE
Jaeger cannot catch the  parameter

### ISSUE THREAD

**Issue by taoskytie** [jaegertracing/jaeger#750]
I build a spring-boot demo project, and i  use jaeger to monitor the request.
for example ,i start a GET request:localhost:8082/sayhello?name=Helen. the jaeger UI display the URL :localhost:8082/sayhello in tags, but  miss the parameter "name=Helen"
this is my pom file:
			<groupId>io.opentracing.contrib</groupId>
			<artifactId>opentracing-spring-web-autoconfigure</artifactId>
			<version>0.2.1</version>

			<groupId>com.uber.jaeger</groupId>
			<artifactId>jaeger-core</artifactId>
			<version>0.25.0</version>
What can I do to make the jaeger UI display the parameter in the span 
I look forward to replies!

**Comment by jpkrohling** [comment]
Please, use the mailing list or gitter for such questions. 

For your specific case, the component in question is the OpenTracing Servlet instrumentation, but I don't think it provides a way to record *all* the query parameters (which might not be a good thing to do anyway). 

What you probably want is to manually add `name` as a tag to the span, like it's done here:

https://github.com/jpkrohling/delivery-service-swarm-backend/blob/master/src/main/java/deliveryservice/backend/rest/control/LocatorService.java#L24

Instead of the tag `wait`, you'd have `name`.

**Comment by pavolloffay** [comment]
Thanks for reporting, this has nothing to do with jaeger, it's an instrumentation issue. The best is to ask on https://gitter.im/opentracing/public or directly in repo for `opentracing-spring-web-autoconfigure`. 

There are multiple ways how you can add tag to a span. A tag being URL with query params or basically anything. 

You can provide a bean for: 
https://github.com/opentracing-contrib/java-spring-web/blob/master/opentracing-spring-web/src/main/java/io/opentracing/contrib/spring/web/interceptor/HandlerInterceptorSpanDecorator.java#L28 or `ServletFilterSpanDecorator`, note that if you do so you have to also provide a bean for standard tags/logs. 

The other solution is to implement custom servlet filter and add a tag there. You can use `tarcer.activeSpan()` to get the current server span.

**Comment by yurishkuro** [comment]
Some people also have conceptual objections to recording query params as too sensitive, e.g. Census does not capture it intentionally. Personally I think it should be a configuration feature of the tracer to automatically strip query params if the app considers them sensitive, but instrumentation should still record the full URL.
