### ISSUE TITLE
Make Elasticsearch index prefix configurable

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#799]
If the index prefix was configurable people could deploy {collector, query} per k8s namespace and use one elasticsearch deployment.

Related to https://github.com/jaegertracing/jaeger-kubernetes/issues/85

**Comment by CpuID** [comment]
+1 would love to see this added.

Our specific use case is using Elasticsearch with AZ specific ES clusters in EC2 (to avoid cross AZ replication $), while using Cross Cluster Search nodes to aggregate jaeger-query searches across N x AZ specific clusters. We do the same now with Logstash and it works great, but we use an index format like `purpose-az-date` to namespace correctly, as opposed to what jaeger supports now of `purpose-date`.

I assume the main item is making [these](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/spanstore/reader.go#L37-L38) configurable, as opposed to constants. I wonder if it's worth enforcing the two `jaeger-span-` + `jaeger-service-` prefixes, and just allow an extra namespace string between the prefix and the date? This would suit both the k8s use case in [this GH issue](https://github.com/jaegertracing/jaeger-kubernetes/issues/85) as well as our use case of AZ specific clusters, I suspect this may be flexible enough while using a single namespace config rather than two (one for spans + one for services)?

@pavolloffay would you be open to a PR for this as a first step?

**Comment by golonzovsky** [comment]
just to mention [spark-dependencies](https://github.com/jaegertracing/spark-dependencies/blob/master/jaeger-spark-dependencies-elasticsearch/src/main/java/io/jaegertracing/spark/dependencies/elastic/ElasticsearchDependenciesJob.java#L147) job as well

**Comment by CpuID** [comment]
> just to mention spark-dependencies job configuration and jaeger-dependencies-* indexes as well

noting there's 3 (known) different index name patterns in use, makes me think the namespace string between the prefix and the date is the safer solution here.

I'm happy to dive into a PR for at least parts of this, but would love some feedback from @pavolloffay or @yurishkuro re the proposed direction before proceeding.

**Comment by yurishkuro** [comment]
related #840

**Comment by yurishkuro** [comment]
my preference is to do it in one go, because as discussed in #840 it requires coordinated changes in 3 places, which if not made would leave some components unable to handle the modified index naming.

**Comment by CpuID** [comment]
@yurishkuro perfectly valid, thx for weighing in. I'll drop some comments on #840 - feel free to close this in favour of the PR.
