### ISSUE TITLE
Pin dependencies that do not use semver to specific commits

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#887]
As decided on the last call https://docs.google.com/document/d/1ZuBAwTJvQN7xkWVvEFXj5WU9_JmS5TPiNbxCJSvPqX0/edit#heading=h.xdsshpxv2gpd

**Comment by burmanm** [comment]
At least gogo/protobuf should be parked, otherwise tests will break. At least on my machine, ``version: 30cf7ac33676b5786e78c746683f0d4cd64fa75b`` works, but with glide update one gets: ``version: 100ba4e885062801d56799d78530b73b178a78f3`` and that one breaks with error message ``invalid character 'A' looking for beginning of value`` from integration_test.go (storage-integration-test target)

Although that could be a sign of something else as well. Just reporting it here in case someone else runs to that issue (I had real fun finding it).

**Comment by bhavin192** [comment]
As we have switched to `dep` in  #1240. I can see only one dependency which says `branch = master` which is `github.com/crossdock/crossdock-go`. I think this issue can be closed.

**Comment by yurishkuro** [comment]
@bhavin192 thanks for checking.
